"""Cross-arm differential harness: replay the shared golden corpus.

Loads ``conformance/differential-corpus.json`` (generated by
python/tools/gen_differential_corpus.py) and asserts the Python arm reproduces
every expected output. The Rust arm replays the same file
(rust/tests/differential.rs), so the two implementations are pinned to identical
wire output for these pure, deterministic operations.
"""

import json
from pathlib import Path

import base64 as _b64

from yamp import auth, callout, capability, config, content, doctor, errors, filters, icap, namespace, pool, schema, security, server, signing, status, subscriptions, tap, tasks, variants

CORPUS = json.loads(
    (Path(__file__).resolve().parents[1] / "conformance" / "differential-corpus.json").read_text()
)


def _pair(resolved):
    return list(resolved) if resolved is not None else None


DISPATCH = {
    "namespace_prefix": lambda v: namespace.prefix(v["id"], v["name"]),
    "namespace_split": lambda v: _pair(namespace.split(v)),
    "namespace_prefix_uri": lambda v: namespace.prefix_uri(v["id"], v["uri"]),
    "namespace_split_uri": lambda v: _pair(namespace.split_uri(v)),
    "signing_canonical": lambda v: signing.canonical(v).decode("utf-8"),
    "signing_sign": lambda v: signing.sign(v["secret"], v["record"]),
    "signing_chain": lambda v: signing.chain(v["prev"], v["record"]),
    "capability_compose": lambda v: capability.compose_capabilities(v["backends"], v["client"]),
    "variants_compose": lambda v: variants.compose_variants(v["backends"]),
    "variants_bind_cursor": lambda v: variants.bind_cursor(v["variant"], v["cursors"]),
    "variants_selected": lambda v: variants.selected_variant(v),
    "variants_available": lambda v: variants.available_variants(v),
    "auth_code_challenge": lambda v: auth.code_challenge(v),
    "auth_token_exchange_request": lambda v: auth.token_exchange_request(v["subject_token"], v.get("audience"), v.get("scope")),
    "filter_resolve_failure": lambda v: filters.resolve_failure(v),
    "filter_deny_response": lambda v: filters.deny_response(v["id"], v["reason"]),
    "filter_chain_outcome": lambda v: filters.chain_outcome(v["verdicts"], v["request"]),
    "base64_encode": lambda v: _b64.b64encode(bytes.fromhex(v)).decode("ascii"),
    "base64_decode": lambda v: _b64.b64decode(v, validate=True).hex(),
    "content_blocks": lambda v: content.blocks(v),
    "content_set_text": lambda v: content.set_text(v["message"], v["path"], v["text"]),
    "content_set_bytes": lambda v: content.set_bytes(v["message"], v["path"], bytes.fromhex(v["bytes"])),
    "interest_match": lambda v: filters.interested(v["interest"], v["context"]),
    "message_context": lambda v: filters.message_context(v["message"], v["direction"]),
    "preview_slice": lambda v: filters.preview(bytes.fromhex(v["data"]), v["n"]),
    "preview_resolve": lambda v: filters.preview_resolve(v["decision"], v["ieof"]),
    "callout_request": lambda v: callout.callout_request(v["context"], v["phase"], bytes.fromhex(v["content"]), v["ieof"]),
    "callout_digest": lambda v: callout.content_digest(bytes.fromhex(v)),
    "callout_budget": lambda v: callout.exceeds_budget(v["size"], v["max_bytes"]),
    "callout_parse": lambda v: callout.parse_verdict(v["response"], v["failure_policy"]),
    "icap_mode": lambda v: icap.icap_mode(v),
    "icap_to_callout": lambda v: icap.icap_to_callout(v),
    "icap_should_deref": lambda v: icap.should_deref(v["kind"], v["enabled"]),
    "server_list_directives": lambda v: server.list_directives(v["ttl_ms"], v["cache_scope"]),
    "server_attach_directives": lambda v: server.attach_directives(v["result"], v["ttl_ms"], v["cache_scope"]),
    "schema_validate": lambda v: schema.is_valid(v["schema"], v["value"]),
    "error_reason": lambda v: errors.reason(v),
    "error_object": lambda v: errors.error_object(v["code"], v.get("detail")),
    "error_describe": lambda v: errors.describe(v),
    "pool_admit": lambda v: pool.admit(v["in_flight"], v["cap"]),
    "pool_deadline": lambda v: pool.deadline(v["now_ms"], v["idle_ms"]),
    "pool_expired": lambda v: pool.expired(v["deadline_ms"], v["now_ms"]),
    "pool_cancel_id": lambda v: pool.cancel_request_id(v),
    "pool_progress_token": lambda v: pool.progress_token(v),
    "task_augmented": lambda v: tasks.is_task_augmented(v),
    "task_new_id": lambda v: tasks.new_task_id(v),
    "task_handle": lambda v: tasks.task_handle(v["task_id"], v["status"], v.get("result"), v.get("error")),
    "subscription_updated": lambda v: subscriptions.updated_notification(v),
    "subscription_namespace_updated": lambda v: subscriptions.namespace_updated(v["message"], v["backend_id"]),
    "server_output_cap": lambda v: server.exceeds_output_cap(v["result"], v["max_bytes"]),
    "doctor_check": lambda v: doctor.check_server(v["tools"], v["protocol_version"]),
    "doctor_render": lambda v: {"text": doctor.render_text(v["findings"], v["mode"]), "ok": doctor.servable(v["findings"], v["mode"])},
    "status_snapshot": lambda v: status.snapshot(v["backend_ids"], v["sessions"]),
    "config_explain": lambda v: config.explain(v["raw"], v["key"]),
    "config_explain_line": lambda v: config.explain_line(v),
    "config_effective": lambda v: config.effective(v["raw"]),
    "config_diff": lambda v: config.diff(v["left"], v["right"]),
    "config_diff_line": lambda v: config.diff_line(v),
    "security_is_loopback": lambda v: security.is_loopback(v),
    "security_check_bind": lambda v: security.check_bind(v["host"], v["has_client_auth"]),
    "config_adapt": lambda v: config.adapt(v),
    "tap_redact": lambda v: tap.redact(v),
    "tap_capture": lambda v: tap.capture(v["direction"], v["message"]),
    "config_error_catalog": lambda v: config.error_catalog(),
    "config_diagnose_slug": lambda v: (config.diagnose(v) or {}).get("slug"),
}


def test_differential_corpus_matches_python_arm():
    cases = CORPUS["cases"]
    assert cases, "corpus is empty"
    for case in cases:
        got = DISPATCH[case["op"]](case["in"])
        assert got == case["out"], f"{case['op']}: {got!r} != {case['out']!r}"


def test_corpus_covers_every_dispatchable_op():
    # Guard against a stale corpus that silently drops an operation's coverage.
    present = {case["op"] for case in CORPUS["cases"]}
    assert present == set(DISPATCH)
